version: "3"

services:
  rabbitmq-management:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq-manager
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 8080:15672
      - 5672:5672
